### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by eutampieri**
I'm working to this plugin and in the meantime this is a PR that fixes some vulns (according to nmp audit). Let me know if you prefer separate pull requests or a big one with all my work

### CODE REVIEW

**Comment by mitch7391** [comment]
@eutampieri  will you be picking up this repo and continuing to work on it?

**Comment by eutampieri** [comment]
I frankly don’t know… I’m willing to review PRs and I liked to implement different bulb types (as I own them), plugs and adaptive lighting, but I don’t know if I’ll have enough time for all of this. It could help if you could give me a quick overview of what’s where.

**Comment by mitch7391** [comment]
I think a lot of us on here would like to see all those features properly implemented. I would love to help but have very limited knowledge myself, but I do know the dev @kpsuperplane was looking for someone to take over the repo... Maybe they can guide you through it?

**Comment by eutampieri** [comment]
In the meantime I've taken out the pywizlight definitions into [this repo](https://gitlab.com/eutampieri/wiz-definitions#wiz-smart-home-definitions), so that they can be used to recognize other bulb types

**Comment by mitch7391** [comment]
@eutampieri any luck on further work with this?

**Comment by kpsuperplane** [comment]
No longer relevant due to platform rewrite, thank you though!

**Pull request closed without merging**
